SQL part 1 exercise
gilRoz23/hibob-academy pull request #11
Opened 2024-09-08 12:07 UTC by gilRoz23

2024-09-09 19:15 UTC, mayhuberman requested changes

2024-09-09 19:15 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091500__create_owners_table.sql
> +    employee_id int
employee_id in bob is type string

2024-09-09 19:15 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091500__create_owners_table.sql
> +)
missing index

2024-09-09 19:15 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091400__create_pets_table.sql
> +);
missing index

2024-09-09 19:15 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091400__create_pets_table.sql
> +create table pets
the name of the file should be the date it was created

2024-09-09 19:15 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091500__create_owners_table.sql
> +create table owners
same here

2024-09-09 19:15 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091400__create_pets_table.sql
> +delete from pets where name='Garfield'
Delete pet by id

2024-09-09 19:15 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091400__create_pets_table.sql
> +-- SELECT * from pets where date_of_arrival<'2023-09-08';
this is not the query - Get the pets that arrived more than a year ago
this query brings all pets that arrived before '09-08-2023'

2024-09-09 19:15 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091400__create_pets_table.sql
> +INSERT INTO pets VALUES(1,"Garfield","cat",2,"2024-09-08");
it wont work the same id for Murphy and Garfield

2024-09-09 19:15 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091400__create_pets_table.sql
> +INSERT INTO pets VALUES (1,"Murphy","dog",1,"2024-09-08");
put these queries in different file

2024-09-10 17:45 UTC, mayhuberman requested changes

2024-09-10 17:45 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091400__create_pets_table.sql
> +    type varchar(255),
should be not null
think what fields should be not null

2024-09-10 17:45 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091400__create_pets_table.sql
> +    company_id integer,
company_id in bob is bigint

2024-09-10 17:45 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091400__create_pets_table.sql
> +CREATE INDEX idx_company_id ON pets (company_id);
add the name of the table to the index name

2024-09-10 17:45 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091500__create_owners_table.sql
> +    name varchar,
same here think what fields should be not null

2024-09-10 17:45 UTC, mayhuberman commented on src/main/kotlin/com/hibob/AcademyApplication.kt
> -import org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
no need for it on this pr

2024-09-10 17:45 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091500__create_owners_table.sql
> +-- CREATE INDEX idx_company_id ON owners (company_id);
missing index

2024-09-11 08:16 UTC, mayhuberman commented on src/main/resources/db/migration/V202408091500__create_owners_table.sql
> +    company_id int NOT NULL,
bigint

2024-09-12 07:43 UTC, rakreshet approved these changes

2024-09-12 07:43 UTC, merged